/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <GLES2/gl2.h>
/* Header for class com_anative_application_flappybirdandroid_Game */

#ifndef FLAPPYBIRDANDROID_GAMEJNI_H
#define FLAPPYBIRDANDROID_GAMEJNI_H

//global game pointer reference
jlong gGamePtr = 0;

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    instantiate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_createNativeObject
        (JNIEnv *, jobject, jint, jint, jobject, jstring);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_destroyNativeObject
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    loadProperties
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_loadProperties
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    loadTexturesFromFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_loadTexturesFromFile
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    initGameObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_initGameObjects
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    initRendererObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_initRendererObjects
        (JNIEnv *, jobject);
/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    processInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_processInput
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_update
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_render
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    screenTouched
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_screenTouched
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    clearTextures
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_clearTextures
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    clearShaders
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_clearShaders
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    loadSoundEffects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_loadSoundEffects
        (JNIEnv *, jobject);

/*
 * Class:     com_anative_application_flappybirdandroid_Game
 * Method:    startSoundManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anative_application_flappybirdandroid_Game_startSoundManager
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif //FLAPPYBIRDANDROID_GAMEJNI_H